version: "3.9"
    
services:
  db:
    image: mysql
    volumes:
      - /home/quoctuan/Projects/Management-CSM/Database:/home/quoctuan/test-db/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123#A
      MYSQL_DATABASE: quanly_csm
      MYSQL_USER: admin
      MYSQL_PASSWORD: abc123#A
    ports:
      - "3306:3306"