version: "3.9"
    
services:
  db:
    image: postgres
    volumes:
      - /home/quoctuan/Projects/Management-CSM/Database:/home/quoctuan/test-db/
    restart: always
    environment:
      POSTGRES_DATABASE: quanly_csm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abc123#A
    ports:
      - "5433:5432"