-- Insert default Ethnicity
INSERT INTO dan_toc_entity(ten) values("Kinh");
INSERT INTO dan_toc_entity(ten) values("Tày");
INSERT INTO dan_toc_entity(ten) values("Thái");
INSERT INTO dan_toc_entity(ten) values("Mường");
INSERT INTO dan_toc_entity(ten) values("Khmer");
INSERT INTO dan_toc_entity(ten) values("Hoa");
INSERT INTO dan_toc_entity(ten) values("Nùng");
INSERT INTO dan_toc_entity(ten) values("H'Mông");
INSERT INTO dan_toc_entity(ten) values("Dao");
INSERT INTO dan_toc_entity(ten) values("Gia Rai");
INSERT INTO dan_toc_entity(ten) values("Ê Đê");
INSERT INTO dan_toc_entity(ten) values("Ba Na");
INSERT INTO dan_toc_entity(ten) values("Sán Chay");
INSERT INTO dan_toc_entity(ten) values("Chăm");
INSERT INTO dan_toc_entity(ten) values("Cơ Ho");
INSERT INTO dan_toc_entity(ten) values("X� Đăng");
INSERT INTO dan_toc_entity(ten) values("Sán Dìu");
INSERT INTO dan_toc_entity(ten) values("Hrê");
INSERT INTO dan_toc_entity(ten) values("Ra Glai");
INSERT INTO dan_toc_entity(ten) values("Mnông");
INSERT INTO dan_toc_entity(ten) values("Thổ");
INSERT INTO dan_toc_entity(ten) values("Xtiêng");
INSERT INTO dan_toc_entity(ten) values("Khơ mú");
INSERT INTO dan_toc_entity(ten) values("Bru - Vân Kiều");
INSERT INTO dan_toc_entity(ten) values("Cơ Tu");
INSERT INTO dan_toc_entity(ten) values("Giáy");
INSERT INTO dan_toc_entity(ten) values("Tà Ôi");
INSERT INTO dan_toc_entity(ten) values("Mạ");
INSERT INTO dan_toc_entity(ten) values("Giẻ-Triêng");
INSERT INTO dan_toc_entity(ten) values("Co");
INSERT INTO dan_toc_entity(ten) values("Chơ Ro");
INSERT INTO dan_toc_entity(ten) values("Xinh Mun");
INSERT INTO dan_toc_entity(ten) values("Hà Nhì");
INSERT INTO dan_toc_entity(ten) values("Chu Ru");
INSERT INTO dan_toc_entity(ten) values("Lào");
INSERT INTO dan_toc_entity(ten) values("La Chí");
INSERT INTO dan_toc_entity(ten) values("Kháng");
INSERT INTO dan_toc_entity(ten) values("Phù Lá");
INSERT INTO dan_toc_entity(ten) values("La Hủ");
INSERT INTO dan_toc_entity(ten) values("La Ha");
INSERT INTO dan_toc_entity(ten) values("Pà Thẻn");
INSERT INTO dan_toc_entity(ten) values("Lự");
INSERT INTO dan_toc_entity(ten) values("Ngái");
INSERT INTO dan_toc_entity(ten) values("Chứt");
INSERT INTO dan_toc_entity(ten) values("Lô Lô");
INSERT INTO dan_toc_entity(ten) values("Mảng");
INSERT INTO dan_toc_entity(ten) values("Cơ Lao");
INSERT INTO dan_toc_entity(ten) values("Bố Y");
INSERT INTO dan_toc_entity(ten) values("Cống");
INSERT INTO dan_toc_entity(ten) values("Si La");
INSERT INTO dan_toc_entity(ten) values("Pu Péo");
INSERT INTO dan_toc_entity(ten) values("Rơ Măm");
INSERT INTO dan_toc_entity(ten) values("Brâu");
INSERT INTO dan_toc_entity(ten) values("Ơ Đu");